msg-node-nodejs:
    image: msg-node-rethink:latest
    volumes:
        - /home/nico/Dev/rethink/dev-msg-node-nodejs:/usr/src/app
    ports:
        - "9090:9090"
    environment:
        - url=localhost
        - port=9090
        - domainRegistryUrl=http://localhost:4567
        - logLevel=INFO
        # - logDir=/usr/src/app/logs
        # - useSSL=1
        # - sslCertificate=/usr/src/app/ssl/myCert.crt
        # - sslPKey=/usr/src/app/ssl/myCert.key

registry-domain:
    image: registry-domain-rethink:latest
    ports:
        - "4567:4567"
    environment:
        - STORAGE_TYPE=RAM
        - EXPIRES=3600

# proxy:
#     image: nginx-rethink:latest
#     volumes:
#         - /home/nico/Dev/rethink/dev-runtime-core:/var/www/html/runtime-core
#         - /home/nico/Dev/rethink/dev-service-framework:/var/www/html/service-framework
#         - /home/nico/Dev/rethink/dev-runtime-browser:/var/www/html/runtime-browser
#         - /home/nico/Dev/rethink/dev-hyperty-toolkit:/var/www/html/hyperty-toolkit
#         - /home/nico/Dev/rethink/logs:/var/log/nginx
#         - /home/nico/Dev/rethink/app-smart-business:/var/www/html/smart-business
#     ports:
#         - "8080:80"
#         - "8443:443"
